---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/name: custom-cluster-name
    app.kubernetes.io/component: cluster-customization
    app.kubernetes.io/part-of: platform-management

resources:
- ClusterClaim_custom-cluster-name.yaml
