---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/name: cluster-gitops
    app.kubernetes.io/component: cluster-management

# NOTE: setting chart home as a workaround for https://github.com/argoproj/argo-cd/issues/8008
helmGlobals:
  chartHome: charts/cluster-management-gitops

# install cluster capabilities
helmCharts:
- name: application-set
  version: 3.0.0
  repo: "file://../../../capabilities/helm/charts/application-set"
  valuesFile: application-set_values.yaml
