---
applicationSetManagedByArgoCDNamespace: openshift-gitops

applicationSetDefaults:
  componentLabel: cluster-management
  partOfLabel: platform-management
  argoCDProject: cluster-management
  syncPolicyAutomated: true
  preventCascadingDeletion: false

applicationSetGitSources:
# cluster specific capabilities
- name: cluster-workload31r5sno
  repoURL: http://rhel9-02.rh.wwtpoc.local:8080/gitops/nautilus-gitops-2.git
  revision: main
  path: clusters/workload31r5sno/capabilities/**/kustomization.yaml

# group-all capabilities
- name: group-all
  repoURL: http://rhel9-02.rh.wwtpoc.local:8080/gitops/nautilus-groups.git
  revision: main
  path: kustomize/groups/all/capabilities/**/kustomization.yaml

# group-test capabilities
- name: group-test
  repoURL: http://rhel9-02.rh.wwtpoc.local:8080/gitops/nautilus-groups.git
  revision: main
  path: kustomize/groups/test/capabilities/**/kustomization.yaml
