apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hello-world-secret-test
  namespace: external-secrets-operator
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-vault
  data:
    - secretKey: target_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: hello-world
        metadataPolicy: None
        property: key
  target:
    name: hello-world-secret-test
