---
# kubernetes cat bundle  
K8S_AUTH_SSL_CA_CERT: /etc/ssl/certs/ca-bundle.crt

# Used for ldap and API cert configs
# catalog_dir: "{{ playbook_dir }}/kustomize-dir"

#chrony_server_list:
#  - 10.1.7.125

# OpenShift installer settings
#openshift_install:
#  log_level: debug                       #  (e.g. "debug | info | warn | error") (default "info")

# Update with customer info
# group_sync:
#   ns: ldap-sync
#   sync_config_url: ldaps://ldap.url.domain.org:636
#   usersQuery:
#     baseDN: "DC=domain,DC=org"
#   groupsQuery:
#     baseDN: "OU=DomainOU,DC=domain,DC=org"

# operatorhub:
#   operator_source: redhat-operators
#   ocp_main_ver: 4.12

# storage:
#   storageclass: vmwarelvs

# ca_bundle_crt: |
#     -----BEGIN CERTIFICATE-----
#     CA_BUNDLE_CRT_STUFF
#     -----END CERTIFICATE-----

# quay_crt: |
#     -----BEGIN CERTIFICATE-----
#     QUAY_CERT
#     -----END CERTIFICATE-----
