---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/part-of: platform-management

resources:
# deploy customer cluster name
# NOTE: after init this is enforced via the clusters/labhub application
- ../../../clusters/labhub/capabilities/custom-cluster-name

# deploy cluster repo configuration
- ../../../clusters/labhub/capabilities/acm-policies-openshift-gitops/cluster-gitops-repository-configuration

# initial configuration of cluster gitops (aka, configure OpenShift GitOps (ArgoCD) for cluster management)
# NOTE: after init this is enforced by governance component
- https://github.com/RHConsulting0/openshift-vsphere-ipi-install.git//day2/capabilities/kustomize/bases/acm-policies-openshift-gitops/policy-manifests/cluster-management/configure-cluster-gitops?ref=automation

# initial deployment of governance policy content for TODO
# NOTE: after init this is enforced by governance component
- https://github.com/RHConsulting0/openshift-vsphere-ipi-install.git//day2/capabilities/kustomize/bases/acm-policies-openshift-gitops/policy-manifests/cluster-management/deploy-cluster-management-applications?ref=automation

# Update Application deployed by TODO to use the gitops configuration supplied by the labhub cluster-gitops-repository-configuration overlay
# NOTE: after init this is done by dynamic replacement by the deploy-cluster-management-applications policy
replacements:
- path: Application-replacement_gitopsRepository.yaml
- path: Application-replacement_gitopsRevision.yaml

patches:
- target:
    name: 00-cluster-management-root
  path: Application-patch_gitops-path.yaml
