---
- name: Initialize gitops reconciliation loop
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: Establish GitOps loop
      ansible.builtin.import_role:
        name: init_gitops
