---
- name: Prepare to execute initialize cluster
  hosts: localhost
  connection: local
  gather_facts: true
  become: false

  tasks:
    - name: Prep for cluster installation
      ansible.builtin.import_role:
        name: prep_cluster_install

