---
- name: Validate OpenShift Cluster and Manage kubeconfig
  hosts: localhost
  connection: local
  gather_facts: true
  become: false

  tasks:
    - name: Validate Cluster and Kubeconfig
      ansible.builtin.import_role:
        name: validate_cluster_and_kubeconfig
